name: pr-agent

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - ready_for_review
      - synchronize
  issue_comment:

concurrency:
  group: pr-agent-${{ github.event.pull_request.number || github.event.issue.number || github.ref }}
  cancel-in-progress: true

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  pr-agent:
    if: ${{ github.event.sender.type != 'Bot' && (github.event_name != 'issue_comment' || github.event.issue.pull_request) }}
    runs-on: ubuntu-latest
    steps:
      - name: run pr-agent
        uses: qodo-ai/pr-agent@v0.34
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          OPENAI_KEY: ${{ secrets.OPENAI_KEY }}
          github_action_config.auto_review: "true"
